name: AWS CDK  CI/CD

on:
 push:
   branches: ['master', 'main']
 pull_request:
   branches: ['master', 'main']

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_DEFAULT_REGION: "ap-southeast-1"

jobs:
  build:
    # if: github.event.pull_request.merged == true
    name: Deploy AWS CDK Cloudfront , SSL Certificate & Route53
    runs-on: ubuntu-latest
    steps:
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Install Node
        uses: actions/setup-node@v3.5.0

      - name: Install Dependencies
        run: npm ci
      
      - name: Install AWS CDK globally
        run: npm install aws-cdk 

      - name: Build CDK Stack
        run: npm run build

      - name: Bootstrap CDK Stack
        run: npx cdk bootstrap

      - name: Deploy AWS CDK Stack
        run: "npx cdk deploy --require-approval never --no-asset-metadata"